# Отключает экранирование Unicode в идентификаторах параметризованных тестов,
# чтобы в выводе терминала корректно отображались русские символы.

[pytest]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
